### ISSUE TITLE
Exception in debugger_thread

### ISSUE THREAD

**Issue by drewcrawford** [AnarchyTools/SublimeAnarchyDebug#1]
When I attempt to start the debugger, I get the following error:

```
Exception in thread debugger_thread:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "/Users/drew/Library/Application Support/Sublime Text 3/Packages/SublimeAnarchyDebug/debug.py", line 111, in debugger_thread
    project_settings.get('working_dir', project_path).replace('${project_path}', project_path)
  File "./xmlrpc/client.py", line 1090, in __call__
  File "./xmlrpc/client.py", line 1419, in __request
  File "./xmlrpc/client.py", line 1132, in request
  File "./xmlrpc/client.py", line 1143, in single_request
  File "./xmlrpc/client.py", line 1255, in send_request
  File "./xmlrpc/client.py", line 1285, in send_content
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "./http/client.py", line 822, in connect
  File "./socket.py", line 435, in create_connection
  File "./socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 61] Connection refused
```

what have I done wrong?

@dunkelstern

**Comment by drewcrawford** [comment]
The answer is, I have not cloned the submodule.  However, after cloning the submodule, I get

```
state change unknown -> stopped,signal
state change stopped,signal -> exited
Exception <Fault 1: "<type 'exceptions.OverflowError'>:in method 'SBThread_GetFrameAtIndex', argument 2 of type 'uint32_t'">
exception [Errno 61] Connection refused
```

**Comment by dunkelstern** [comment]
Ok that overflow error is killing me... officially... I know what went wrong, fixing tomorrow.

Did you compile with `-g`? else the debugger can't set a breakpoint and the program runs and probably just exits.

Mental note: variables in stack trace do not use `getSummary` but `getValue`, that probably bombs for Swift `Int` and `Int64`

**Comment by drewcrawford** [comment]
No change in behavior after compiling with `-g`

**Comment by dunkelstern** [comment]
Try updating to master branch (+ update submodule). Probably fixed it, at least i can't reproduce it now.

**Comment by drewcrawford** [comment]
Still fresh on 82a1b30d2ff72fa94a96b616c18aba1e952a7c82
Submodule 1581b5826bcc645b9d0b759483b76bb022a1338d

**Comment by lucteo** [comment]
Hi

Tried to install this from Sublime package manager. I get the same error each time I try to start the debugger. I have a C++ project, and I'm compiling it with Debug.

Best regards,
LucTeo

**Comment by SethArchambault** [comment]
Same issue!

**Comment by johnsturgeon** [comment]
Just wanted to throw my two cents in, I was having this error to, and the issue was somewhat easy to fix.  I removed the compiled package that I installed using package control, and then I cloned this repo (using --recursive to make sure to get the bridge submodule), then dropped the directory in my Packages folder.  Now .. there are a couple other issues that I will comment on separately, but at least I got past this error.

**Comment by lpasarel** [comment]
I was facing the same issue:

root cause in my particular case was lldb_server.py not starting
> ImportError: No module named **lldb**

In order to solve the issue lldb python modules needs to be made visible to the Sublime python env

Thanks to this [plugin](https://packagecontrol.io/packages/Environment%20Settings), I was able to easy add lldb to PYTHONPATH in my *.sublime-project.
In my case lldb is part of Xcode app:
```json
"settings":
  {
    "env":
    {
      "Darwin":
      {
      "PYTHONPATH": "$PYTHONPATH:/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python"
      },
    }
  }
````
