### ISSUE TITLE
Possible to debug any obj-c project?

### ISSUE THREAD

**Issue by johnsturgeon** [AnarchyTools/SublimeAnarchyDebug#4]
I've been looking for lldb integration with Sublime Text for some time, Is it possible to use this plugin for debugging a project I build (using xcodebuild) that's just obj-c?

I've tried following the instructions and I've set the 'executable' to [DerivedData]/Build/Products/Debug/MyApp.app/Contents/MacOS/MyApp

in the SublimeAnarchyDebug settings, but all I get when I try to start the debugger is:

```
Exception in thread debugger_thread:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "debug in /Users/---/Library/Application Support/Sublime Text 3/Installed Packages/SublimeAnarchyDebug.sublime-package", line 111, in debugger_thread
  File "./python3.3/xmlrpc/client.py", line 1099, in __call__
  File "./python3.3/xmlrpc/client.py", line 1428, in __request
  File "./python3.3/xmlrpc/client.py", line 1141, in request
  File "./python3.3/xmlrpc/client.py", line 1152, in single_request
  File "./python3.3/xmlrpc/client.py", line 1264, in send_request
  File "./python3.3/xmlrpc/client.py", line 1294, in send_content
  File "./python3.3/http/client.py", line 1061, in endheaders
  File "./python3.3/http/client.py", line 906, in _send_output
  File "./python3.3/http/client.py", line 844, in send
  File "./python3.3/http/client.py", line 822, in connect
  File "./python3.3/socket.py", line 435, in create_connection
  File "./python3.3/socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 61] Connection refused

```

**Comment by drewcrawford** [comment]
May be a duplicate of #1

**Comment by johnsturgeon** [comment]
Thanks for getting back to me, but I'm not sure what the fix is there?  is there a workaround?

**Comment by drewcrawford** [comment]
Don't believe there's a fix, cc: @dunkelstern

**Comment by dunkelstern** [comment]
I have some time to look into this this weekend, i assume that the program exits before the debugger can get it to suspended state. So it just exits and has never the time to connect, therefore the "connection refused".

I'll get back to that tomorrow ;)

**Comment by johnsturgeon** [comment]
Great!  Thank you.. also, can I confirm that I'm 'doing this right'.
1. I'm doing objective-c development
2. I installed anarchy tools (on my mac) - was this necessary?
3. I installed SublimeAnarchy and SublimeAnarchyDebug
4. I modified my sublime project file to add:

```
    "settings": {
        "SublimeAnarchyDebug": {
            "debug": {
                "executable": "<DerivedDataDir>/Build/Products/Debug/MyApp.app/Contents/MacOS/MyApp"
                "params": [
                ],
                "path": [
                ],
                "environment": [
                ],
                "working_dir": "${project_path}"
            }
        }
    }

```
1. I ran 'AnarchyDebug: start debugging in sublime text

Is that all that's required?  Are there any other dependancies?  Should this work with a non-Swift project?

Thank you

**Comment by drewcrawford** [comment]
atbuild/atpkg etc. should not be necessary for this usecase (debugging a program built elsewhere)

As far as I know, debugging ObjC should work just like debugging Swift (or not work, as seems to be the case).

As I recall, the issue in #1 is that @dunkelstern was not able to reproduce the behavior, he is the one with the most experience in this component, so that prevented much forward progress.

If that persists, and if I can still reproduce, I may be able to look into this separately – a broken debugger is not ideal for my workflow either ;-)

**Comment by johnsturgeon** [comment]
If there is anything I can do to help the debugging effort please let me know

**Comment by johnsturgeon** [comment]
If there is anything I can do to help the debugging effort please let me know

**Comment by johnsturgeon** [comment]
Any update on this?
