### ISSUE TITLE
Issue with launching the debugger.

### ISSUE THREAD

**Issue by jaroslov** [AnarchyTools/SublimeAnarchyDebug#5]
I'm a complete noob at sublime text 3 + packages + anything else. Anyways, I'm trying to launch the debugger, and in the console I get this error:

`no command for selector: noop:
Exception in thread debugger_thread:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "debug in /Volumes/Higgin/jnsmith/Library/Application Support/Sublime Text 3/Installed Packages/SublimeAnarchyDebug.sublime-package", line 111, in debugger_thread
  File "./python3.3/xmlrpc/client.py", line 1099, in __call__
  File "./python3.3/xmlrpc/client.py", line 1428, in __request
  File "./python3.3/xmlrpc/client.py", line 1141, in request
  File "./python3.3/xmlrpc/client.py", line 1152, in single_request
  File "./python3.3/xmlrpc/client.py", line 1264, in send_request
  File "./python3.3/xmlrpc/client.py", line 1294, in send_content
  File "./python3.3/http/client.py", line 1061, in endheaders
  File "./python3.3/http/client.py", line 906, in _send_output
  File "./python3.3/http/client.py", line 844, in send
  File "./python3.3/http/client.py", line 822, in connect
  File "./python3.3/socket.py", line 435, in create_connection
  File "./python3.3/socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 61] Connection refused`

It looks like there's an issue connecting to python? I think the default python3 that comes with macos is python3.6.1; not sure if that is an issue.

**Comment by SethArchambault** [comment]
I also have this issue:

```
Exception in thread debugger_thread:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "debug in /Users/watchmyfeet/Library/Application Support/Sublime Text 3/Installed Packages/SublimeAnarchyDebug.sublime-package", line 111, in debugger_thread
  File "./python3.3/xmlrpc/client.py", line 1099, in __call__
  File "./python3.3/xmlrpc/client.py", line 1428, in __request
  File "./python3.3/xmlrpc/client.py", line 1141, in request
  File "./python3.3/xmlrpc/client.py", line 1152, in single_request
  File "./python3.3/xmlrpc/client.py", line 1264, in send_request
  File "./python3.3/xmlrpc/client.py", line 1294, in send_content
  File "./python3.3/http/client.py", line 1061, in endheaders
  File "./python3.3/http/client.py", line 906, in _send_output
  File "./python3.3/http/client.py", line 844, in send
  File "./python3.3/http/client.py", line 822, in connect
  File "./python3.3/socket.py", line 435, in create_connection
  File "./python3.3/socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 61] Connection refused
```

**Comment by lpasarel** [comment]
have a look on #1  which seems to track the same issue signature
