### ISSUE TITLE
Entirely fails on many issues - most notably an XML RPC fault on debugger launch.

### ISSUE THREAD

**Issue by tillt** [AnarchyTools/SublimeAnarchyDebug#7]
- Installed version from PackageManager misses the submodules - hence dead on arrival
- defaults are incorrectly named in `Main.sublime-menu`
```
diff --git a/Main.sublime-menu b/Main.sublime-menu
index 433b313..6f9619a 100644
--- a/Main.sublime-menu
+++ b/Main.sublime-menu
@@ -17,7 +17,7 @@
                         [
                             {
                                 "command": "open_file",
-                                "args": {"file": "${packages}/SublimeAnarchyDebug/SublimeAnarchy.sublime-settings"},
+                                "args": {"file": "${packages}/SublimeAnarchyDebug/SublimeAnarchyDebug.sublime-settings"},
                                 "caption": "Settings – Default"
                             },
                             {
```
- after having adapted the settings with
```
{
  // Path to the LLDB.framework python resources
  "lldb_python_path": "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python",

  // Automatically show lldb console when debugger starts?
  "auto_show_lldb_console": true
}
```
- launch debugger fails with
```
Exception in thread debugger_thread:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/till/Library/Application Support/Sublime Text 3/Packages/SublimeAnarchyDebug/debug.py", line 111, in debugger_thread
    project_settings.get('working_dir', project_path).replace('${project_path}', project_path)
  File "./python3.3/xmlrpc/client.py", line 1099, in __call__
  File "./python3.3/xmlrpc/client.py", line 1428, in __request
  File "./python3.3/xmlrpc/client.py", line 1141, in request
  File "./python3.3/xmlrpc/client.py", line 1156, in single_request
  File "./python3.3/xmlrpc/client.py", line 1327, in parse_response
  File "./python3.3/xmlrpc/client.py", line 658, in close
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.NotImplementedError'>:Wrong number of arguments for overloaded function 'SBTarget_Launch'.\n  Possible C/C++ prototypes are:\n    Launch(lldb::SBTarget *,lldb::SBListener &,char const **,char const **,char const *,char const *,char const *,char const *,uint32_t,bool,lldb::SBError &)\n    Launch(lldb::SBTarget *,lldb::SBLaunchInfo &,lldb::SBError &)\n">
```

**Comment by maddanio** [comment]
is this project still active?

**Comment by tillt** [comment]
@maddanio obviously not.

**Comment by dunkelstern** [comment]
No this project is not active anymore, as i am not using sublime text anymore. If you want to fix it/take it over comment herr
